### ISSUE TITLE
Ejections not immidiately absorbed

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/Petri#3]
Since i've made ejections such a useful weapon, this is rather important.

Ejections, when moving, pass right through players... but only sometimes.

**Comment by vram4** [comment]
That is because ejected mass's position (and whether that position collides with a player) is calculated every 50 ms. If the cell is very small (less than 100), theres a possibility that the traveling points of the ejected mass will not touch the cell therefore looking like it passes right through (same issue affects viruses). This system was implemented because i felt that it was too costly to calculate whether or not player cells intersected with the line of fire.

**Comment by yrsegal** [comment]
Perhaps too costly, but I've made viruses and ejections such useful weapons (viruses are more dangerous, ejections slow the hit person down) that i need calculation like this. Could you point me to the commit/section of file where you did this?

**Comment by vram4** [comment]
Youre going to have to add those calculations. Currently with each tick in the movement system, the new position for player cells are calculated. Then player cells check for any node that collides with them, including ejected cells. It would be best to add the calculations by adding code to override calcMovePhys() in entity/EjectedMass.js as that is where the calculations for new positioning is made. (The base function is in entity/Cell.js at line 223)

As for viruses, the code that allows ejected mass to "interact" with them can be found at line 683 in GameServer.js of my fork. Each time a new position for ejected mass is found, all viruses are checked for collision. Since the base mass of a virus is 100 and the base speed for ejected mass is 160, there is a chance of passing through (speed decays so eventually the speed of ejected mass will be lower than 100).
